### ISSUE TITLE
java.lang.UnsupportedOperationException: nth not supported on this type: JButton$Tag$fd407141

### ISSUE THREAD

**Issue by rainecheck** [ogri-la/strongbox#149]
On startup, `wowman` throws the following error. Was working OK last night, so probably something broken from the most recent update.
Running Manjaro.

```
2020-06-01 05:20:18.161 svirfneblin INFO [wowman.core:1301] - starting app
2020-06-01 05:20:18.220 svirfneblin INFO [wowman.ui.gui:951] - starting gui
2020-06-01 05:20:18.364 svirfneblin ERROR [wowman.main:22] - Uncaught exception on main
                 wowman.main.main                  
                              ...                  
                wowman.main/-main     main.clj: 170
                wowman.main/-main     main.clj: 175
                              ...                  
                wowman.main/start     main.clj:  47
                wowman.main/start     main.clj:  52
              wowman.ui.gui/start      gui.clj: 952
           wowman.ui.gui/start-ui      gui.clj: 876
          wowman.ui.gui/mk-tabber      gui.clj: 711
    wowman.ui.gui/installed-panel      gui.clj: 586
wowman.ui.gui/configure-app-panel      gui.clj: 379
                              ...                  
             seesaw.mig/mig-panel      mig.clj:  44
             seesaw.mig/mig-panel      mig.clj:  63
       seesaw.core/abstract-panel     core.clj: 940
       seesaw.core/abstract-panel     core.clj: 939
     seesaw.options/apply-options  options.clj: 136
    seesaw.options/apply-options*  options.clj: 129
      seesaw.options/apply-option  options.clj: 114
         seesaw.mig/add-mig-items      mig.clj:  31
                              ...                  
java.lang.UnsupportedOperationException: nth not supported on this type: JButton$Tag$fd407141
```

**Comment by torkus** [comment]
thankyou for raising the issue @rainecheck 

I have a suspicion who the culprit is. It didn't complain about the pre-release but I don't recall checking it after the 1.0 release, so sorry for the inconvenience.

`wowman` will continue to receive fixes like this for a while.

**Comment by torkus** [comment]
@rainecheck , if it's not too much of a problem, could you test this and see if it works for you?

---

[wowman-0.12.5-unreleased-standalone.jar.zip](https://github.com/ogri-la/strongbox/files/4710296/wowman-0.12.5-unreleased-standalone.jar.zip)
sha256: c376423c34262984b2ae839620c024bdeee74dd9b74f9c53089181a8e13deafb

---

you can run it with just `java -jar wowman-0.12.5-unreleased-standalone.jar.zip` (no need to remove `.zip` extension).

I'll be able to do a proper release in a few hours.

**Comment by torkus** [comment]
wowman version 0.12.5 has been released. Thanks for raising the bug @rainecheck
