### ISSUE TITLE
Can't find my addon?

### ISSUE THREAD

**Issue by marmalodak** [ogri-la/strongbox#152]
I haven't played wow in 10+ years, so I feel I must be missing something, corrections welcome.

I installed strongbox, found bartender4 with 42 bazillion downloads, clicked it, clicked install, and lots of things happened in my log file, but after restarting wow, I do not see the widget, nor do I see any installed addons from strongbox.

Please pardon me if I missed a step like "Click the big blue button that says Do What I Mean."

**Comment by torkus** [comment]
If you haven't played in 10+ years then you may not be aware the addons directory has changed. Strongbox doesn't auto-detect where your addons directory is, you have to choose it yourself.

The old path would have looked like `/path/to/WoW/Interface/Addons`.

The new path looks like `/path/to/WoW/_retail_/Interface/Addons` (or `_classic_` for classic WoW).

After installing the addon, it should appear in strongbox in the list of your installed addons. It should also be present in the directory you selected as your addon directory.

> and lots of things happened in my log file
> Please pardon me if I missed a step like "Click the big blue button that says Do What I Mean."

Tone aside, if you want to faceroll your way through life I would suggest a Mac and a lobotomy.

I'm happy to help if you if you can be helpful in return. Were any of the log messages red and say `error` ...? I need more to work with.

**Comment by torkus** [comment]
feel free to re-open this issue with more information

**Comment by marmalodak** [comment]
Torkus, thanks for answering my question.

Indeed, I didn’t know I needed to choose the add-on path, that was the single biggest source of my confusion. Thanks for the clarification.

I’m sorry I left a bad impression, I was trying self-deprecating humor by referencing [DWIM](http://www.catb.org/~esr/jargon/html/D/DWIM.html) specifically “DWIM is often suggested in jest as a desired feature for a complex program; it is also occasionally described as the single instruction the ideal computer would have”.

It took me a while to answer this because

1. I didn’t have time to play
2. Your comments about face rolling hurt and I was trying to understand whether I have the stomach to participate in discussions on the wide-open internet or in the game specifically

**Comment by torkus** [comment]
> Indeed, I didn’t know I needed to choose the add-on path

you may be interested in this ticket: https://github.com/ogri-la/strongbox/issues/159

> Your comments about face rolling hurt

I apologise. I must have misread the tone of your comment. 

If you're after a WoW community then I suggest reddit: https://old.reddit.com/r/wow/
