### ISSUE TITLE
[Suggestion] Rename "WoW directory" button to "Addon directory"

### ISSUE THREAD

**Issue by BloodyIron** [ogri-la/strongbox#159]
As someone just starting to use this tool, it was not self-explanatory that I had to find the Addons folder when hitting this button, and I think a change of language will help with other newbies too. Just a small change, could be nice for the next release.

**Comment by torkus** [comment]
I'll consider it, thank you for opening a ticket.

**Comment by BloodyIron** [comment]
You're welcome! This is really the only GUI Addon tool I can use on Linux right now, so figured I'd help where I can :) Fast response btw! :D

**Comment by torkus** [comment]
Just a lucky coincidence :)

I maintain [a list of other addon managers](https://ogri-la.github.io/wow-addon-managers/) you might find helpful if strongbox doesn't work for you.

**Comment by BloodyIron** [comment]
> Just a lucky coincidence :)
> 
> I maintain [a list of other addon managers](https://ogri-la.github.io/wow-addon-managers/) you might find helpful if strongbox doesn't work for you.

Neat! Thus-far though strongbox is working fabulously for me :D

**Comment by torkus** [comment]
Is this more helpful?

![Screenshot at 2020-06-24 17-17-46](https://user-images.githubusercontent.com/48790775/85517740-b474c300-b63e-11ea-8030-311428526b69.png)

**Comment by BloodyIron** [comment]
I think it's not quite there, I do think "Add-on directory" or "Addon directory" is fully clear.

**Comment by torkus** [comment]
done, it will be part of `1.1.0` when it gets released

**Comment by BloodyIron** [comment]
Woot!

**Comment by torkus** [comment]
This change has just been released as part of 1.1.0. Thank you for opening a ticket about it.

**Comment by BloodyIron** [comment]
Yay!
