### ISSUE TITLE
Visual: the folder dropdown menu is too short to be useful

### ISSUE THREAD

**Issue by yourfate** [ogri-la/strongbox#166]
**Describe the bug**
The drop down menu where you select which wow installation to display truncates the path so that I can't see which is which. Even in the open drop down or with mouse over I can't see which is which.

**Expected behavior**
There is plenty of space, make the box longer, at least when opening the drop down, or show it in the tool tip.
![dropdown](https://user-images.githubusercontent.com/47528796/87836494-92164400-c890-11ea-836c-ee30b35dc2fb.png)

**Additional Info**
The resolution is 2560x1440 if that's important.

**Comment by torkus** [comment]
I'll take a look, thanks for opening an issue, @yourfate .

**Comment by layday** [comment]
I remember that I limited the width of folder dropdown in #78 because with a sufficiently long path it would get clipped and the track dropdown and folder button wouldn't be visible.  On macOS, the full path is visible when you click on the dropdown.  I had not realised this wouldn't be the case on other OSes.

**Comment by torkus** [comment]
I test with very short directories like `/home/torkus/bar` so I never really see the problem.

**Comment by torkus** [comment]
useful or too ugly to even mention?

![Screenshot at 2020-07-19 22-04-50](https://user-images.githubusercontent.com/48790775/87874790-ebef4900-ca0b-11ea-97fd-fa33c767f769.png)

the tooltips should be possible as well as lengthening the dropdown to a percentage of the overall width, but still may not be long enough for linux users with wine prefixes (like in the screenshot).

replacing `/home/$username/` with `~/` could help a little, but I don't think any other sort of abbreviation would work.

I'll try adding the directories to one of the menus and see how that works.

It might even need it's own custom dialog, in which case it wouldn't in the next release.

**Comment by layday** [comment]
I don't think that works very well on a conceptual level - it might lead one to think that there is one tab for every add-on folder.  What if you placed the folder dropdown on a separate line above 'Refresh', 'Update all' and the track dropdown, and increased the width to occupy the available space.  This would also introduce a kind of visual hierarchy, where refreshing, updating and changing tracks are tasks specific to the selected folder.  In the same vein, I would rename 'Addon directory' to '_Add_ addon directory' to indicate that you're not replacing the path but adding a new one.

**Comment by torkus** [comment]
Thank you for the feedback, @layday . I'll have a further play. 

The `addon directory` button was renamed recently. Perhaps *"New addon directory"*

**Comment by torkus** [comment]
I quite like this:

![Screenshot at 2020-08-08 12-10-28](https://user-images.githubusercontent.com/48790775/89700783-319a9400-d970-11ea-849a-52e9474dc337.png)

And shifting the 'refresh' under *View -> Refresh* and shifting the 'addon directory' button under *File -> New addon directory*

I'll add tildes for the user's home directories as well to make the path slightly shorter.

**Comment by torkus** [comment]
Fixed. I didn't end up adding tildes because it looked so strange and didn't really save much space vs the amount of extra code required.

Thanks again for opening a ticket.
