### ISSUE TITLE
add support for wago.io and TSM

### ISSUE THREAD

**Issue by mspykerez** [ogri-la/strongbox#172]
Possible to add wago.io to update auras and Plater profiles/scripts like WeakAuras Companion (similar to what this does: https://github.com/AcidWeb/CurseBreaker) ?

Also ability to update TradeSkillMaster data (similiar to what this does: https://github.com/camas/grunt) ?

**Comment by torkus** [comment]
Thank you for opening a ticket.

I don't use or really know much about weakauras, you'll have to be more explicit in what you want. Same for TradeSkillMaster.

For example:

1. add a button that does *this* when clicked
2. it sends *this* to *there*
3. it then displays *this* afterwards

Any new features that require scraping HTML probably won't happen so it's needs a structured source of data, preferably a well defined API.

**Comment by layday** [comment]
This [monologue](https://github.com/layday/instawow/issues/39) of mine might be of relevance.  As for the WeakAuras Companion, it's a [desktop app](https://github.com/WeakAuras/WeakAuras-Companion) which fetches updates for auras (mini add-ons which you can import into the main WeakAuras add-on) from https://data.wago.io and places them in an ancillary add-on - also called 'WeakAurasCompanion' - which the main WeakAuras can pull updates from in-game.  CurseBreaker and my own manager replicate its functionality.

**Comment by torkus** [comment]
> similiar to what this does: https://github.com/camas/grunt) ?

> CurseBreaker and my own manager replicate its functionality.

do these need a feature column in [the List](https://ogri-la.github.io/wow-addon-managers/)?

**Comment by layday** [comment]
Could have it there I suppose.  instawow also has version pinning and rollback if you want to add a feature column for either of those.

**Comment by torkus** [comment]
Thanks for opening a ticket @mspykerez and thanks for the context @layday . 

I'm not going to add these because my time and enthusiasm are limited these days and *not* because they are unworthy enhancements.
