### ISSUE TITLE
GUI locks up when attempting to add add-on folder on Mac

### ISSUE THREAD

**Issue by layday** [ogri-la/strongbox#177]
Attempting to add a new add-on folder from the menubar (or by hitting cmd-N) locks up the GUI.  The process itself does not hang and can be exited cleanly.  The log does not reveal anything of relevance with the `--debug` flag or otherwise.  Using Strongbox version 2.0.0 and macOS version 10.14.6.

**Comment by torkus** [comment]
Thanks @layday , I'll take a look

**Comment by torkus** [comment]
I think I found it. Would you mind testing that it works for you now?

---

[strongbox-2.1.0-unreleased-standalone.jar.zip](https://github.com/ogri-la/strongbox/files/5050859/strongbox-2.1.0-unreleased-standalone.jar.zip)
sha256: 8643e84583309a4ca24d494a5095130c11a7a29bb149f5591f9fd68d3a26408a

---

You can run it with `java -jar strongbox-2.1.0-unreleased-standalone.jar.zip`.

I'm also curious if opening and cancelling multiple times on the Import or Export options also causes hanging behaviour for you?

**Comment by layday** [comment]
That seems to have fixed it.  I can confirm that import and export also cause it to hang.

**Comment by torkus** [comment]
Cheers, @layday , this only seems to affect macs unfortunately. I'll get the other dialogues fixed up and do a 2.0.1 release.

**Comment by torkus** [comment]
This has been fixed in 2.0.1, closing issue
