### ISSUE TITLE
Mark addon as ignored

### ISSUE THREAD

**Issue by DarkVirtue** [ogri-la/strongbox#181]
It would be nice to mark an addon as ignored or not to check.

I have an addon installed that's long dead, gone from Curse, by some miracle still works perfectly, and doesn't have a modern replacement. I'd like to have an option to suppress the warning that Strongbox can't find it.

**Comment by torkus** [comment]
Thanks for opening an issue.

Release 2.0.0 included substantial work to the 'ignore' feature. In the GUI, right click the addon you want to ignore and it will become greyed out. Other addons won't be able to override it and you won't be able to accidentally update or uninstall it (via strongbox).

**Comment by DarkVirtue** [comment]
Ah, thanks for pointing that out.
