### ISSUE TITLE
Option to automaticallly remove zips

### ISSUE THREAD

**Issue by DarkVirtue** [ogri-la/strongbox#182]
A toggle option to always automatically remove the zip files for completed downloads would be appreciated.

I have a script in place to automatically backup my WTF and Interface directories. I think it would make more sense to have Strongbox clean up the zips when done than remember to hit the button myself or add it to my backup script.

**Comment by torkus** [comment]
The slow accumulation of zip files does need to be addressed.

What I might do is store in them in the cache directory and only keep the most recent around.

This enhancement may be a while in coming, I'm working on replacing the GUI this month.

**Comment by torkus** [comment]
This is part of the 3.1.0 release.

To turn it on go to `Preferences` -> `Remove addon zip after installation` and click it. 

This will delete zip files downloaded for that addon after successful installation.

If you wipe all the zip files and turn this on you should be set.

Thanks again for opening a ticket.
