### ISSUE TITLE
Warning for Ignored Addon Strongbox Can't Find

### ISSUE THREAD

**Issue by DarkVirtue** [ogri-la/strongbox#183]
**Describe the bug**
Strongbox still logs a warning about addons it can't find in the catalog.

**To Reproduce**
1. Install an addon that's no longer in Curse/WoWInt/etc.
2. Tell Strongbox to ingore the addon.
3. Strongbox still issues a warning it can't find the addon in the catalog.

**Expected behavior**
I would expect Strongbox to not worry at all about ignored addons, even if they're not in the catalogs.

**Comment by DarkVirtue** [comment]
[debug.log](https://github.com/ogri-la/strongbox/files/5081220/debug.log)

The addon in question is named "TimeToDie"

**Comment by torkus** [comment]
Fixed. It will be part of the 3.1.0 release. 

Apologies for the long delay on this one.

**Comment by torkus** [comment]
Another bug came up so the fix for this was released sooner in 3.0.1
