### ISSUE TITLE
Option to force retail version to be installed in a classic folder

### ISSUE THREAD

**Issue by Llamatron2112** [ogri-la/strongbox#185]
There is a few retail addons that work with classic, it would be nice to have a way to force install a retail version of a specific addon in a classic addons folder.
Here's an example of such an addon I use: https://www.curseforge.com/wow/addons/eens-chat-window-backup

**Comment by torkus** [comment]
Thanks for opening a ticket.

There is a way to do this currently but I understand what you're saying about supporting it properly. I have plans to add a 'force install' type option in the future, this ticket will be boost it's priority.

For now, switch your addon directory to 'retail', find and install the retail addon you want, then switch it back to classic.

**Comment by torkus** [comment]
There are now two new options that can be picked from, "any, prefer retail" and "any, prefer classic":

![Screenshot at 2020-11-11 11-52-44](https://user-images.githubusercontent.com/48790775/98753505-6d804200-2414-11eb-8f66-554f4acb618b.png)

In your case @Llamatron2112 , you would want "any, prefer classic".

This will be released as part of 3.1.0.

**Comment by Llamatron2112** [comment]
Excellent, thanks a lot ! I will probably check it once 3.1 is released

**Comment by torkus** [comment]
3.1.0 has been released, thanks again for opening a ticket
