### ISSUE TITLE
UI 3.0 feedback

### ISSUE THREAD

**Issue by eVen-gits** [ogri-la/strongbox#192]
First off, I really like the redesign - it looks more modern. I am here to give some constructive feedback in order to make it even better (in my opinion).
![image](https://user-images.githubusercontent.com/2612606/95894280-248f8c00-0d89-11eb-9d6c-a6edc6d86b07.png)

1) I think you might want to set minimum size for these elements. A lot of users (including myself) have a 1080p monitor and having the window resized to a "reasonable" size results in texts not fitting. Perhaps minimum size on "update" button and wow version combo box. Similarly, I would change the "path" combo box to be truncated on the left instead of right, but that is really minor.

2) The black text on a dark gray is rather hard to read.

3) Similarly, I think there might be a better color selection for addon sources (yellow is very contrastic).

4) The row size in the log is now larger, which results in less info being visible (although it's just blank space). I would reduce the row height in this case. Perhaps even allow toggling of the output.

Other than that, it looks like a very nice update. Thank you for your hard work!

**Comment by torkus** [comment]
thank you for the feedback, @eVen-gits , they're all good points.

Targeting 1080p is sensible and it's what the default window size is out of the box. I use a tiling window manager so I never see it's initial size and it tends to get overlooked. I'll see how narrow I can make it in general though. The important thing is that the very wide path drop down is still legible as it's difficult to truncate it's contents.

> I would change the "path" combo box to be truncated on the left instead of right, but that is really minor.

it's position won't change but I think I can avoid it's truncation altogether. 

> The black text on a dark gray is rather hard to read.

The dark theme didn't get much love but I'll give it a second pass before release.

> Similarly, I think there might be a better color selection for addon sources (yellow is very contrastic).

If you want to have a muck around in Gimp/Krita/Inkscape for me and come up with a better theme I'd love to see it.

I guess the dark theme is for those who are using bright monitors for gaming (or who just prefer a dark desktop theme ;), so I'll tweak things in that direction.

> The row size in the log is now larger, which results in less info being visible (although it's just blank space). I would reduce the row height in this case. Perhaps even allow toggling of the output.

The log window may be coming to an end in an upcoming release, or at least shifted to it's own tab. For now it's easily re-sizable - just drag that big black bar splitting the two windows. I'll also take a look at how much room it uses at 1080p - I don't think your screenshot is using full height.

**Comment by eVen-gits** [comment]
> If you want to have a muck around in Gimp/Krita/Inkscape for me and come up with a better theme I'd love to see it.

> I guess the dark theme is for those who are using bright monitors for gaming (or who just prefer a dark desktop theme ;), so I'll tweak things in that direction.

Hey!

I know you are probably limited to java/swing interface, but I took a little while to play with qt to remake your layout, but using qt which supports multiple platforms (windows, linux, mac). It really just uses my system's theme, but here's how it looks:

![image](https://user-images.githubusercontent.com/2612606/96021518-d7c2b880-0e4f-11eb-9d73-4ec9701b70ae.png)

Naturally, some adjustments could be made, but making a sleek UI in qt is really quick (I use it in combination with python - pyqt).

Perhaps, I would just look into "Dracula" theme, that has a wide array of supported programs listed:

- https://draculatheme.com/
- https://github.com/dracula/dracula-theme

**Comment by torkus** [comment]
Nice work! Yes, it's a little galling to have QT whip up a GUI in no time flat ;) I'm envious of their ecosystem but there isn't much interoperability between Java/Clojure and QT unfortunately. I think KDE do a *huge* amount right but they still never managed to win me over. I've done some Python+PyQT years ago and it was a good experience.

I see nothing wrong here, I'll riff off of the colours and fill in the blanks. Thanks for the effort, @eVen-gits

**Comment by torkus** [comment]
this is about as short and narrow as I can get it (500x536px) before the top menu starts truncating it's items.

![Screenshot at 2020-10-16 22-04-26](https://user-images.githubusercontent.com/48790775/96253759-b56d9e00-0ffb-11eb-8972-a171bce295b1.png)

it's kind of cute. Ellipses now occur on the left for the menu and the update-all and game track drop downs have a min width.

**Comment by eVen-gits** [comment]
Looks great!

You mind showing how dark theme looks on your system? I do believe it's desktop environment specific.

**Comment by torkus** [comment]
I'm working on the dark theme changes now. I'll post a screenshot and do another pre-release when they're done

**Comment by torkus** [comment]
it's not 1:1 with your screenshot but I think it will do for now. Do you see any glaring problems?

![Screenshot at 2020-10-17 00-11-34](https://user-images.githubusercontent.com/48790775/96265764-67619600-100d-11eb-9c57-0959eb684044.png)

**Comment by eVen-gits** [comment]
That was some quick work!

No it looks excellent! Well done, this looks like a significant upgrade over previous design. Really nicely done.

Looking forward to using it! Thanks!

**Comment by torkus** [comment]
3.0.0 with it's new dark theme has been properly released.

Thanks again.

**Comment by eVen-gits** [comment]
Awesome! Getting that immediately!
