### ISSUE TITLE
Still won't open on Mac OS X Catalina

### ISSUE THREAD

**Issue by Fred-IV** [ogri-la/strongbox#202]
Not sure if I can reopen a closed case, but the problem is still there. I have to open it with the terminal command; 
java -jar /Applications/World\ of\ Warcraft/strongbox-3.0.1-standalone.jar --ui gui1

Trying to double-click it to open it gives an error box;

The Java JAR file “strongbox-3.0.1-standalone.jar” could not be launched.

**Comment by torkus** [comment]
thank you for opening a ticket.

Could you run two commands from the terminal for me please.

1. java -version
2. java -jar /Applications/World\ of\ Warcraft/strongbox-3.0.1-standalone.jar 

and paste the output here. It could be you're using an older version of Java

**Comment by Fred-IV** [comment]
Running it that way, it works, and Dark Mode too. I can fix the bad with
the other command probably.
The last way with gui1 it was stuck in light mode.

It still doesn't run from double-clicking the .jar file though.
Thank

java -jar /Applications/World\ of\ Warcraft/strongbox-3.0.1-standalone.jar

WARNING: cat already refers to: #'clojure.core/cat in namespace:
net.cgrand.parsley.fold, being replaced by: #'net.cgrand.parsley.fold/cat

2020-10-24 08:03:41.144 Freds-Mac-Pro.local INFO [strongbox.core:1191] -
starting app

2020-10-24 08:03:41.472 Freds-Mac-Pro.local INFO [strongbox.core:840] -
pruning http cache

2020-10-24 08:03:41.504 Freds-Mac-Pro.local INFO [strongbox.utils:26] -
instrumentation is OFF

starting gui

2020-10-24 08:03:42.045 Freds-Mac-Pro.local INFO [strongbox.core:551] -
loading installed addons: /Applications/World of
Warcraft/_retail_/Interface/AddOns

2020-10-24 08:03:42.050 Freds-Mac-Pro.local INFO [strongbox.core:681] -
loading catalogue: full

2020-10-24 08:03:43.201 Freds-Mac-Pro.local INFO [strongbox.core:724] -
matching 20 addons to catalogue

2020-10-24 08:03:43.567 Freds-Mac-Pro.local INFO [strongbox.core:740] - num
installed 20 , num matched 16

2020-10-24 08:03:43.568 Freds-Mac-Pro.local WARN [strongbox.core:743] - you
need to manually search for them and then re-install them

2020-10-24 08:03:43.568 Freds-Mac-Pro.local WARN [strongbox.core:744] -
failed to find 4 addons in the 'full' catalogue: chatcopypaste,
explorercoords, acegui-3.0-selectable-panel,
prat-|cff8080ff3.0|r-|r[|cffeda55flibraries|r]

2020-10-24 08:03:43.569 Freds-Mac-Pro.local INFO [strongbox.core:794] -
checking for updates

2020-10-24 08:03:43.610 Freds-Mac-Pro.local INFO [strongbox.core:799] - 16
addons checked, 5 updates available



Also, it just updated again today, which is confusing now that I checked
the version, because the date's behind.

java --version

java 14.0.1 2020-04-14

Java(TM) SE Runtime Environment (build 14.0.1+7)

Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)


So, I just tried with my terminal command, and I fixed the title bar to
dark.
java -Dapple.awt.application.appearance=system -jar /Applications/World\
of\ Warcraft/strongbox-3.0.1-standalone.jar

Everything's much better, except, again, for some reason, it has to be run
from the terminal. No double-click, which, if I want Dark Mode, I guess
that's ok.
The old command I was running, the interface wasn't as nice.


Thanks!

**Comment by Fred-IV** [comment]
[image: image.png]

This is using my saved terminal command;
java -Dapple.awt.application.appearance=system -jar /Applications/World\
of\ Warcraft/strongbox-3.0.1-standalone.jar

**Comment by torkus** [comment]
Thanks for the reply, Fred. It's a little difficult to understand, but from what I can tell:

* you have the latest version of Java installed (14)
* strongbox works
* dark mode works

Your current problem is that double-clicking the `.jar` file doesn't open it.

I don't use macOS regularly but it could be that `java` isn't set to open `.jar` files by default. It might also be that you are seeing something that I'm not (your image failed to upload) by using `-Dapple.awt.application.appearance=system`. I have tested that and I don't know what it does.

On Windows and some Linux desktop environments you can change the handler for certain file types, usually by right-clicking the file and selecting `open with` or similar.

It's also possible to use a shell script to run strongbox with the options you like. Put this into a file:

```shell
#!/bin/bash
java -Dapple.awt.application.appearance=system -jar /Applications/World\of\ Warcraft/strongbox-3.0.1-standalone.jar
```

save it as `strongbox` and make the file executable in the file's properties. Double clicking it should now work.

> The old command I was running, the interface wasn't as nice.

There are two GUIs available, the original GUI called `gui1` that you can access with `--ui gui1` and the current one that was released as part of strongbox `3.0.0`.

**Comment by torkus** [comment]
How're you getting along, Fred? Figured out your problems yet? Need help with anything specific?

**Comment by torkus** [comment]
I'm closing this until there is something concrete for me to fix. Good luck
