### ISSUE TITLE
Dark Mode on Mac?

### ISSUE THREAD

**Issue by Fred-IV** [ogri-la/strongbox#203]
Any chance of getting Dark Mode to work on the Mac?
Selecting it in the menu changes the text color, as would be required for Dark Mode, but it doesn't actually put the window in dark mode.
I was able to get just the title bar dark launching it with this command;
java -Dapple.awt.application.appearance=system -jar /Applications/World\ of\ Warcraft/strongbox-3.0.1-standalone.jar --ui gui1

But, that's the most I have been able to do...

**Comment by torkus** [comment]
Could you send me a screenshot of what you're seeing?

>  --ui gui1

ah, you're using the original gui. It won't be receiving updates any more and will be removed eventually. It's just there while any bugs with the new interface are ironed out.

The dark mode in gui1 was created for users of linux using specific desktop environments. It didn't work out too well ultimately.

**Comment by torkus** [comment]
I'm going to close this in favour of your other issue, Fred.
