### ISSUE TITLE
mac, 3.0.1 crashes/exits without warning

### ISSUE THREAD

**Issue by tstirrat** [ogri-la/strongbox#206]
**Describe the bug**
The app randomly exits, unsure why. 

The most recent time I clicked a curseforge addon link and it exited in the background before I could come back.
Another time I opened it in the background and never activated the window, about 2 mins later I went to find it and it was gone.

**To Reproduce**
*Steps to reproduce the behavior. For example:*
1. Open strongbox
2. Change to another app and wait
3. It's gone after a minute or two

**Expected behavior**
It should stay open in the BG

**Screenshots**
N/A

**Additional context**
[debug.log](https://github.com/ogri-la/strongbox/files/5526694/debug.log)

**Comment by torkus** [comment]
Thanks for opening a ticket, @tstirrat , I'll investigate

**Comment by torkus** [comment]
sorry for the delay, November has been very busy.

I can recreate this. It's a mystery so far but I'm going to try a few things and see if I can get a stacktrace or syslog or something.

**Comment by torkus** [comment]
The original gui doesn't appear affected so `java -jar /path/to/strongbox.jar --ui gui1` should be more stable while I figure this one out.

**Comment by tstirrat** [comment]
Ah, thanks!

**Comment by torkus** [comment]
Sorry for the lack of activity on this ticket, it stumped me and it's taken a while for me to circle back around to it. I'm looking at it now.

**Comment by torkus** [comment]
I have a fixed version here: https://github.com/ogri-la/strongbox/releases/tag/issue-206

Could you run it and confirm it works for you, @tstirrat ?

**Comment by torkus** [comment]
Marking this as fixed, it will be released as part of `3.2.0` this week. Let me know if it doesn't work for you.

**Comment by torkus** [comment]
fixed in 3.2.0.

please update this ticket if if it's still not working for you.
