### ISSUE TITLE
Tukui API changes

### ISSUE THREAD

**Issue by layday** [ogri-la/strongbox#215]
Hi @torkus, thought I'd let you know that Tukui have made some changes to their API and the `addon` and `classic-addon` endpoints were removed - you can't look up add-ons by their ID anymore.  The full list endpoints are still available.

**Comment by torkus** [comment]
cheers, @layday , I can see the errors now. It looks like whatever they're responding with isn't JSON and strongbox dumps a stacktrace.

it's bothersome but it looks like all addons are returned in a single unpaginated list? I can work with that, somehow.

**Comment by torkus** [comment]
(want to build a unified, sane, API?)

**Comment by layday** [comment]
Yeah, there's two lists, one for retail and another for classic, plus the two retail suites which are listed separately:

* https://www.tukui.org/api.php?addons
* https://www.tukui.org/api.php?classic-addons
* https://www.tukui.org/api.php?ui=tukui
* https://www.tukui.org/api.php?ui=elvui

The API responds with a content type of `text/html` which is probably what's causing the error.

**Comment by layday** [comment]
> (want to build a unified, sane, API?)

The author of WowUp has been working on something of the sort along with the Ajour guys.  I know he's wrapped the Tukui API, combining the retail suites with the rest of the retail add-ons, if you'd like to reach out to him about using his API instead of Tukui's directly or if you'd like to get involved.  The wrapper API has kept support for fetching add-ons individually:

* https://hub.dev.wowup.io/tukui/retail
* https://hub.dev.wowup.io/tukui/classic
* https://hub.dev.wowup.io/tukui/retail/-2

I would be interested in supporting their effort myself although my knowledge of web services is rather primitive.

**Comment by torkus** [comment]
oh that's cool. I've been thinking about it for years as an attempt to get rid of some crappy code in strongbox, but it keeps coming back to the fact that:

* addon hosts with their own clients don't want us.
* I don't want to be in an adversarial relationship with addon hosts
* centralisation is not the answer
* privacy is important
* strongbox is still just a hobby!

I think I'll continue flying under the radar for a while. I'm worried about those guy's desire for the spotlight.

**Comment by torkus** [comment]
fixed as part of 3.1.1
