### ISSUE TITLE
no release found for 'tradedispenser-classic' (classic) on wowinterface

### ISSUE THREAD

**Issue by rainecheck** [ogri-la/strongbox#219]
**Describe the bug**
Classic release for `tradeDispenser-classic` is not found on wowinterface, despite it being flagged for classic compatibility. I've had to manually install `tradeDispenser-classic`.

**To Reproduce**
Search "tradeDispenser". Attempt to install.

**Expected behavior**
Addons should update or install.

**Additional context**
```
2020-12-09 22:19:09.926 svirfneblin WARN [strongbox.catalogue:60] - no release found for 'tradedispenser-classic' (classic) on wowinterface
```

**Comment by torkus** [comment]
that's strange ... I can see it:

![Screenshot at 2020-12-11 21-11-15](https://user-images.githubusercontent.com/48790775/101893988-6c9a2600-3bf5-11eb-8062-9c5258b25679.png)

could you check that you have one of the 'short', 'full' or 'wowinterface' catalogues selected?

**Comment by torkus** [comment]
oh, re-reading your question I may have misunderstood you. The problem isn't that you can't find the addon, it's that once you've found it you can't install it?

In that case, you should know that wowinterface and marking addons as being either classic or retail is pretty bad. For `tradeDispenser-classic` it's probably marked as 'retail', so if your game track is 'classic' and you get that message:

> no release found for 'tradedispenser-classic' (classic) on wowinterface

then it's probably marked as 'retail'.

if this is all correct, with release 3.1.0 you can now change the game track to `any, prefer classic` that should solve this problem.

if you're on an older version of strongbox and don't want to upgrade, you can switch your game track to 'retail', install `tradeDispenser` and then change the game track back to 'classic'.

**Comment by rainecheck** [comment]
I'm on 3.1.1, and that's perfect. Thanks - not a bug, resolved.
