### ISSUE TITLE
Limited pane size when vertically resizing window

### ISSUE THREAD

**Issue by DarkVirtue** [ogri-la/strongbox#229]
**Describe the bug**
When resizing the window vertically past a certain point, the addon list pane stops expanding - instead, the status bar expands and the log pane can be expanded with the grabby bar. This may only affect resolutions/orientations with lots of vertical space, such as 4k or portrait view.

* OS: Kubuntu 20.10
* DE: KDE Plasma 5.19.5
* Java: 11.0.9.1
* Strongbox: 3.2.0

**To Reproduce**
1. Open in a view with substantial vertical room.
2. Resize the Strongbox window vertically.
3. Eventually, the adddon pane will stop growing with the window size.

**Expected behavior**
The addon and log panes should continue to resize proportionally to the window size while the status bar does not change size.

**Screenshots**
![Strongbox_vertical_resize](https://user-images.githubusercontent.com/6946119/103417319-1c045180-4b3f-11eb-82eb-a7828cf92fa4.png)

**Comment by torkus** [comment]
thanks for the illustrated bug report, @DarkVirtue , this is very helpful.

**Comment by torkus** [comment]
thanks for your patience, @DarkVirtue , I've tweaked things slightly and the gui is arranging itself much better now.

![Screenshot at 2021-02-17 17-17-57](https://user-images.githubusercontent.com/48790775/108167093-155c8880-7145-11eb-910d-dbb0df27025d.png)

![Screenshot at 2021-02-17 17-18-24](https://user-images.githubusercontent.com/48790775/108167088-1392c500-7145-11eb-9354-0713327ddc78.png)

This will make it into the 3.3 release sometime soon.

**Comment by torkus** [comment]
strongbox 3.3.0 has been released with this fix in it. Thanks again.
