### ISSUE TITLE
Support for addons from townlong-yak.com

### ISSUE THREAD

**Issue by DarkVirtue** [ogri-la/strongbox#234]
**Describe the solution you'd like**
The addon author cfxfox, probably best known for OPie and Venture Plan, appears to have stopped updating their addons on Curse. Instead, they're updating their addons on their own website: https://www.townlong-yak.com/addons/latest

**Describe alternatives you've considered**
One of the WoWup devs has set up an unofficial mirror of VenturePlan on GitHub here: https://github.com/nod-dev/VenturePlan
Cursebreaker supports townlong-yak.com directly.

**Comment by layday** [comment]
Townlong Yak has an official API described [here](https://www.townlong-yak.com/addons/about/update-api).

**Comment by layday** [comment]
I don't know how strongbox goes about updating add-ons but the TY add-on endpoint is devoid of any information which can be used to compare versions.  The author expects managers to query the update service (`/us`) endpoint with a locally-stored token which should be retrieved from `/us/new` before installing an add-on.  If no updates are available, the response will be empty.  If an update is available, the token is invalidated and you must replace the token, not from `/us/new`, but from the value of `next` in the response body.  You must do this even if the add-on you have installed is not included in the update bundle or be left to (re)trace the trail of tokens with every update check.

**Comment by torkus** [comment]
thanks for opening a ticket @DarkVirtue .

From @layday's feedback it seems checking for updates is a bit involved but not impossible. I don't see a means to fetch a list of available addons though.

From the website I see they have [8 addons](https://www.townlong-yak.com/addons/latest).

I could scrape the HTML I suppose but it's significant work for a boutique addon host with such a small offering.

I could go the Cursebreaker route and use the WowUp API, but I'm leery of creating an indirect dependency by going with a third party API, especially such a new one.

The only thing stopping me from implementing this at the moment is that I tend to work slowly and have a backlog of things to do.

**Comment by wyrmss** [comment]
https://www.townlong-yak.com/addons/venture-plan/release

**Comment by torkus** [comment]
?

**Comment by layday** [comment]
I am being told Townlong Yak will introduce a new API which will behave more similarly to CurseForge.

**Comment by torkus** [comment]
Yeah, I should close this ticket. I can't see any reason to support a site with just 4 addons.
