### ISSUE TITLE
curseforge, "no match!" debug output in console

### ISSUE THREAD

**Issue by torkus** [ogri-la/strongbox#240]
I've left a debug statement in :unamused: 

![Screenshot at 2021-02-20 01-11-02](https://user-images.githubusercontent.com/48790775/108518498-8902bf00-7318-11eb-846c-189933d519c8.png)

low priority, but include fix in the next patch release

**Comment by Powderwt** [comment]
Hey, just curious if there is any projected release date for this next patch that this fix is in? Thanks for all the work you do!!

**Comment by torkus** [comment]
hi @Powderwt, thanks for the question.

strongbox is a hobby, I'm lucky if I have an hour to work on it a night. I usually have a bit more time on weekends. On top of being time constrained I'm also a fairly slow developer as I rely heavily on writing tests and doing some basic QA before merging each feature branch. I don't really have release dates but there was a monthly cadence to the releases last year as the changes I released were fairly small and unambitious.

The next 4.0 release will have some larger changes in it.

Typically you can find what is outstanding for the next release in the "todo" section of my [TODO](https://github.com/ogri-la/strongbox/blob/develop/TODO.md#todo) file. The other sections are "done" and "bucket". The "done" section is what has been completed for the next release, the "bucket" section is literally just a bucket of ideas that I pull from for the next releases. If you want to see anything in particular worked on just open an issue and it will (probably) get a higher priority against everything else.

Regarding this particular bug, a fix for it went in the other day but I can do a patch release if its particularly annoying? I could see how it might be.

>  Thanks for all the work you do!!

and thank you for your patience.

**Comment by Powderwt** [comment]
Oh no, by all means, you do your thing! Haha! It isn't an "issue" for me as much as I was just curious was all. I don't want to interrupt whatever type of rhythm you may have going with everything for such a minor thing lol! 

Just got done reading the "TODO" and it seems like you've got quite a bit planned/in the works, so just keep on doing your thing good sir!

**Comment by torkus** [comment]
fixed in 3.3.1
