### ISSUE TITLE
strongbox not picking up WeakAuras2 TBC version

### ISSUE THREAD

**Issue by jecs** [ogri-la/strongbox#268]
Hello, I was unable to get  the TBC version of WeakAuras2 using github. At first, I thought that it was simply that they didn't include the release on github, so I opened an issue.

I was quickly told that the issue appears to be on strongbox's end, perhaps in the way that TBC is detected.

Here is a link to the [issue](https://github.com/WeakAuras/WeakAuras2/issues/3118) that I opened. One of the contributors to WeakAuras2 narrowed it down to the following code snippet/correction.
```
(let [;; matches 'classic-tbc', 'classic-bc', 'classic_tbc' and 'classic_bc', but not 'classictbc' or 'classicbc'. see tests 
 because strongbox is wrong and needs to be fixed. the official name supported by blizzard, the addon pages and the packager is bcc
```

**Comment by torkus** [comment]
hi @jecs , thanks for opening a ticket.

The problem has to do with figuring out which asset belongs to which 'game track' (retail, classic, classic tbc). Addons hosted on github have no standard or consistent way of indicating what game track they belong to - a lot of guessing and hedging is involved.

A quick first look at the assets attached to that release and I can see the classic tbc asset, `WeakAuras-3.4.2-bcc.zip`, only has `bcc` identifying it as belonging to that game track.

The logic for matching a name to a game track is here if you're curious: 
https://github.com/ogri-la/strongbox/blob/develop/src/strongbox/utils.clj#L611-L615

I don't know if you're a programmer or not, but It's essentially looking for patterns like 'classic-tbc' or 'classic-bc' or 'classic_tbc' or 'classic_bc' or 'tbc' or 'bc' while not being too vague to create false positives.

Unfortunately 'bcc' is not a pattern strongbox currently looks for.

It sounds like you're operating in 'strict' mode so I would recommend:
1. checking your game track is set 'Classic (TBC)'
2. un-ticking 'strict'
3. File -> Import addon from Github -> and paste https://github.com/WeakAuras/WeakAuras2

and this should install *something*. For me, it installs the classic tbc version of WeakAuras as evidenced by the interface version on the 'installed' tab.

I am a bit a unclear on how I got the classic tbc version to install when it couldn't find the game track in the asset name though ... I'll leave this ticket while I investigate and maybe add '-bcc' as a pattern to look for.

**Comment by torkus** [comment]
![Screenshot at 2021-05-29 11-15-35](https://user-images.githubusercontent.com/48790775/120054483-5979f600-c06f-11eb-9a66-a74b5871faf7.png)

**Comment by AcidWeb** [comment]
BigWigs packager started to add `release.json` to all GitHub releases. You have all data you need there.

**Comment by torkus** [comment]
Do all addon authors use BigWigs packager?

**Comment by AcidWeb** [comment]
All? No. But it is crazy popular among the authors and it would be a waste to ignore the data it can provide.

**Comment by jecs** [comment]
Hi, @torkus 

Thank you very much for addressing this issue!

> The logic for matching a name to a game track is here if you're curious:
> https://github.com/ogri-la/strongbox/blob/develop/src/strongbox/utils.clj#L611-L615
> 
> I don't know if you're a programmer or not, but It's essentially looking for patterns like 'classic-tbc' or 'classic-bc' or 'classic_tbc' or 'classic_bc' or 'tbc' or 'bc' while not being too vague to create false positives.

Interesting. I'm not familiar with clojure (more of a C++/python person), but it sounds like you're relying on filenames to detect which WoW client is supported. AcidWeb's suggestion sounds promising.

> Unfortunately 'bcc' is not a pattern strongbox currently looks for.
> 
> It sounds like you're operating in 'strict' mode so I would recommend:

I'm not running in Strict mode. Weakauras has a version check built-in. The classic version simply won't start in the TBC client.

**Comment by torkus** [comment]
> The classic version simply won't start in the TBC client.

Uninstall it and try again (I suspect it's not deterministic) or install it the old fashioned way or use the Curseforge version.

There isn't support for `release.json` or `-bcc` suffixes just yet.

**Comment by jecs** [comment]
> > The classic version simply won't start in the TBC client.
> 
> Uninstall it and try again (I suspect it's not deterministic) or install it the old fashioned way or use the Curseforge version.
> 
> There isn't support for `release.json` or `-bcc` suffixes just yet.

Yes, I am using Curseforge for the time being. Thank you.

**Comment by torkus** [comment]
[fixed here](https://github.com/ogri-la/strongbox/pull/270), this will be part of the 4.2.0 release in the next day or so

**Comment by torkus** [comment]
4.2.0 has been released, support for release.json will make it into a future version. 

Feel free to re-open the ticket (or open another ticket) if you find your problem isn't solved, @jecs
