### ISSUE TITLE
Big thanks for this app !

### ISSUE THREAD

**Issue by hschoepel** [ogri-la/strongbox#278]
Hi,

Just wanted to say a bit thanks for the hard work to you developer. Strongbox runs great on Debian and is the best addon manager i used so far :)

Henrik

**Comment by torkus** [comment]
Thank-you for the compliment, Henrik, I'm pleased it works well for you.

I've been looking into Debian's [new DUR](https://mpr.hunterwittenborn.com) as it resembles Arch's AUR very closely so there may be a more convenient means to install Strongbox in the future.

Feel free to open issues for any features you'd like to see. I have [my own long list of things](https://github.com/ogri-la/strongbox/blob/develop/TODO.md) I want to get done but community feedback helps me prioritise them. 

Thanks again.
