### ISSUE TITLE
Add Gitlab Support

### ISSUE THREAD

**Issue by Ironlenny** [ogri-la/strongbox#303]
I use a number of addons by WobLight. But he distributes exclusively through [Gitlab](https://gitlab.com/users/woblight/projects). He does tag [h]is releases as far as I can tell.

P.S. Would you please delete the other ticket that was open for this request.

**Comment by torkus** [comment]
I took a look at Gitlab (the service, not the software) 2019-12-04 and while the software had a new 'releases' like feature, the service hadn't updated itself yet. 

I took another look about this time last year and found it had improved somewhat.

I'll take another look as part of next month's release and see what we can do.

> P.S. Would you please delete the other ticket that was open for this request.

Done. Your secret is safe with me, Superman ;)

**Comment by Ironlenny** [comment]
Thanks for looking into this and for deleting the other ticket. I also want to thank you for all the work you do on this project.

**Comment by torkus** [comment]
I've done a pre-release here with Gitlab support: https://github.com/ogri-la/strongbox/releases/tag/4.8.0-alpha1

I'd appreciate it if you took a look and let me know if you find any problems.

**Comment by torkus** [comment]
Released as part of 4.8.0
