### ISSUE TITLE
Browse to addon directory

### ISSUE THREAD

**Issue by archer31** [ogri-la/strongbox#350]
**Is your feature request related to a problem? Please describe.**
It is just a bit tedious to navigate to the addon directory anytime I need to install an unsupported addon manually (dang adibags).

**Describe the solution you'd like**
An option to open the addon directory straight from the File menu. `File > Browse addon directory`

**Describe alternatives you've considered**
The alternative currently is top navigate to the addon directory manually

**Additional context**
This would need to be implemented in a system agnostic manner since there are so many different file browsers available on Linux. (Nemo, Nautilus, etc.)

**Comment by torkus** [comment]
hey @archer31 , thanks for opening a ticket. This seems straightforward to implement and I should be able to squeeze it in to this month's release.

Another approach to this problem would be to make 'manual' installation of addons not found in the catalogue easier as well. I'll have a think about a workflow for that and it might make it into next month's release.

> This would need to be implemented in a system agnostic manner since there are so many different file browsers available on Linux. (Nemo, Nautilus, etc.)

For sure. I imagine it working the same way as clicking the hyperlinks work now, by opening your preferred file browser or web browser.

**Comment by torkus** [comment]
short:
![Screenshot at 2022-05-11 08-31-02](https://user-images.githubusercontent.com/48790775/167738530-3d927077-7198-47f1-b9e7-9529e0ff031f.png)

wide:
![Screenshot at 2022-05-11 08-30-37](https://user-images.githubusercontent.com/48790775/167738543-5ece53c7-1a0d-4470-ba08-e12a0d447aa9.png)

what I might do is make this link opt-in and hide it behind a preference in the `Preferences` menu.

**Comment by archer31** [comment]
A possible solution for the manual install would be to allow the user to upload a `.zip` file on their own as an alternative to providing a github link since this wouldn't require the github to list a release.

I do appreciate that the app already shows addons that aren't found in any of the sources.

**Comment by torkus** [comment]
> **Describe the solution you'd like**
> An option to open the addon directory straight from the File menu. `File > Browse addon directory`

This is probably a better, easier, nicer, solution than my hyperlink above. I'll play around with both, see what happens.

> A possible solution for the manual install would be to allow the user to upload a .zip file on their own as an alternative to providing a github link since this wouldn't require the github to list a release.

Strongbox works by consulting the catalogue and then looking online for extra details about the addon, like the newest version and a url to download it from, downloads it, safely installs it and then writes some metadata. Providing a hyperlink via `File -> Import addon` is essentially parsing the URL, looking for it in the catalogue (adding it to the user-catalogue in some cases), downloading, installing, etc. 

When we bypass this workflow and just skip to the installing it part a bunch of assumptions fall over, both in the code and in my mental model of strongbox. I think it's definitely possible, it's [been on my TODO list for a while now](https://github.com/ogri-la/strongbox/blob/3905c5019a7c07514f106dcfe14c3fac0214d4e6/TODO.md?plain=1#L219-L226), it just needs to be investigated.

**Comment by torkus** [comment]
fixed in newly released 5.2.0.

thanks again for opening a ticket, @archer31
