### ISSUE TITLE
Choosing columns scrambles everything

### ISSUE THREAD

**Issue by ilu33** [ogri-la/strongbox#353]
Choosing View - Columns - skinny or fat scrambles the interface. It is not possible to get the default view back, clicking on default does nothing. Choosing individual columns doesn't restore anything, the addon names column stays empty no matter what you do, other columns get mixed up.

**Comment by torkus** [comment]
Thank you for opening a ticket.

This is not behaviour I've ever seen before. Could you post some screenshots of this scrambledness.

If you could tell me what OS and desktop environment you're using that would be helpful, as well as the version of Strongbox that you're using.

**Comment by ilu33** [comment]
I cannot reproduce it. strongbox was almost unrespondent while that happened, so probably some java memory problem.

**Comment by torkus** [comment]
> so probably some java memory problem.

I've not had problems with Strongbox and memory constraints before, even on the tiny mac mini I have to test with. Slowness definitely, but not scrambled columns. Please let me know if it happens again.
