### ISSUE TITLE
install from 'local' source

### ISSUE THREAD

**Issue by ilu33** [ogri-la/strongbox#355]
**Is your feature request related to a problem? Please describe.**
I need to download ZIP files by hand to update some addons and it would be great to automate the installation.

**Describe the solution you'd like**
Add a new install source: a local directory defined by the user where they put the zip files for each game branch, obviously separate for retail, classic and tbc. When the user clicks "update" strongbox would unpack the correspondent ZIP file(s) and copy them into the addon dir. 
**Describe alternatives you've considered**
Ignoring all addons that must be updated by hand. Does not look pretty and does not give you a ToDo list.

**Comment by ilu33** [comment]
No I don't think it's exactly the same, but it's related. I like my idea better.

**Comment by torkus** [comment]
I like that your idea can be used 'offline'. It will definitely be considered.

**Comment by torkus** [comment]
> It might not be the exact feature you describe but it should go a long way towards bulk installation of addons from unsupported sources.

Released in 5.3.0
