### ISSUE TITLE
Option for update check only

### ISSUE THREAD

**Issue by ilu33** [ogri-la/strongbox#356]
**Is your feature request related to a problem? Please describe.**
Some addons are on wowinterface or github but with an older version than locally installed. This might change because we are in a transition phase.

**Describe the solution you'd like**
A new addon option: "Update check only" Check for updates and show the available version number but do not include this addon in update download and install.

**Describe alternatives you've considered**
Ignoring the addon stops the downgrade but does not alert you when wowinterface/gihub catches up.

I would understand if you think this is too much work since "soon" [TM] the transition phase might come to an end.

**Comment by ilu33** [comment]
I meant the transition phase for users which just starts now for most (friend today: "hey, the updater you recommended stopped working today - fix it pls").
Thanks for pointing me at your overview again - if you implement that "install ZIPs from directory" feature some python script with beautifulsoup and cfscrape might help out.

**Comment by torkus** [comment]
> The transition phase for users actually just starts now (friend today: "hey, the updater you recommended stopped working today - fix it pls"). It seems that curse finally disabled the old API.

oh - that's news to me. Far out. I honestly thought Overwolf/Curseforge were just putting on an aggressive front so banning bots wouldn't come as a surprise. Well, they gave us fair warning if nothing else.

**Comment by torkus** [comment]
I'm going to close this issue because I think it's a little too fine-grained for what I want in Strongbox.

Addons can be plain ignored, they can be pinned to specific versions and if the addon comes from a host that supports it, you can install a specific past release again.

Thanks for opening a ticket and explaining what you'd like to see and sorry that I won't be implementing it.
