### ISSUE TITLE
Famous addon not appearing on search result despite being on github

### ISSUE THREAD

**Issue by r4ulill0** [ogri-la/strongbox#384]
I was trying the app for the first time and looked for [Bagnon](https://github.com/Jaliborc/Bagnon). The results only showed plugins for that specific addon but not the main one.
![1672685739](https://user-images.githubusercontent.com/36534958/210269851-c813e032-efe9-4220-8ba4-594c549e2093.png)

Seems like bagnon has releases disabled even though the code is still there. This is all related to the curseforge exclusive thing they are trying to impose. I was wondering if it is possible to automate the management of addons like this one

**Comment by torkus** [comment]
hi there, thanks for opening a ticket.

A few things:
1. the fonts are all screwed up on your strongbox installation, I'd love to know more about the system you're running
2. strongbox can use different *catalogues* and uses a 'short' catalogue by default. There is an older version of Bagnon available on Wowinterface via the 'full' catalogue (`Catalogue` -> `Full`), but this probably doesn't help you.
3. yes, you're right, they're a Curse-only schill and I sympathise - they probably don't appreciate the tall shoulders their addon stands upon or that monetisation/financial compensation is either forbidden or frowned upon by Blizzard.

> I was wondering if it is possible to automate the management of addons like this one

Strongbox can't deal with github repositories like this one in it's current state, with no releases available and nothing to download.

The next best thing would be introducing support for cloning repositories and keeping them updated, probably switching between branches or tags. Can you think of any features you'd like to see if I added support for git repos?

**Comment by torkus** [comment]
Just for reference, the same screen on my system using the 'Full' catalogue:

![Screenshot at 2023-01-03 10-15-28](https://user-images.githubusercontent.com/48790775/210285385-c46ce158-c826-465f-b971-7994bf6fda34.png)

**Comment by r4ulill0** [comment]
About the fonts I have installed arch linux manually so that's how a fontless distro looks I guess. All the icons characters are missing because I didn't installed a font with them.

My $CONFIGHOME/fontconfig/fonts.conf (Hack font isn't installed yet)

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
    <alias>
            <family>sans-serif</family>
            <prefer>
                <family>Noto Color Emoji</family>
                <family>Hack</family>
            </prefer>
        </alias>
        <alias>
            <family>serif</family>
            <prefer>
                <family>Noto Color Emoji</family>
                <family>Hack</family>
            </prefer>
        </alias>
        <alias>
            <family>monospace</family>
            <prefer>
                <family>Noto Color Emoji</family>
                <family>Hack</family>
            </prefer>
    </alias>
</fontconfig>
```

Now, about features. It would be cool if there would be some api to extend or make plugins for, so cases like this one could be managed and dealt one by one with simple scripts and a template to follow. I guess strongbox need some information to check updated state (now by cheking release tab version or some api in wow interface) but it could be a python script that has a function getVersion() and provides that information.

There are some addons that have complex updating processes that would benefit from this, like Trade Skill Master which needs an entire application and extra steps to work properly and it's a pain to update.

The thing is, the more addons a manager supports the better. And if it's robust and flexible even more. I found strongbox looking for alternatives to curseforge but after seen how painful is going to be managing addons in linux I'm starting to plan some way to bypass curseforge exclusiveness (Maybe with selenium and their website, or with scripts and the addons repositories). I could stay without updates for a while too, but it's not like there are other alternatives for my situation other than try to make curseforge work on linux (I'm not gonna even try because they could be making another master move and destroy my setup again anyways).

I hate when community efforts like these have to be strongly monetized...

**Comment by torkus** [comment]
It sounds like you might be interested in a more hackable addon manager. I maintain a list of other addon managers here: https://ogri-la.github.io/wow-addon-managers/

If you select 'unfiltered' from the presets drop down in the top left hand corner you can filter addon managers by programming language.

For example, [here is a list of addon managers written in Python that are still maintained](https://ogri-la.github.io/wow-addon-managers/?preset/name=unfiltered&field/feature-curseforge=&field/maintained=yes&field/software-licence=&field/classic-wotlk=&field/windows=&field/eula=&field/feature-tukui=&field/ads=&field/source-available=&field/feature-wowinterface=&field/ui=&field/language=Python&field/feature-vcs-addons=&field/retail=&field/classic-tbc=&field/linux=&field/f-oss=&field/classic=&field/mac=&field/feature-catalog-search=).

If you discovered other addon managers in your searching that are not on the list I'd love to know about them.

I'll add 'plugin support' to my [TODO](https://github.com/ogri-la/strongbox-catalogue-builder/blob/master/TODO.md) file for consideration but if it does happen it won't be any time soon.

There has been some success in getting the Curse client running under Wine from what I hear.

**Comment by torkus** [comment]
The missing font issue fixed here: https://github.com/ogri-la/strongbox/pull/388

I'll close this issue when it gets a release.
