### ISSUE TITLE
Issues updating ElvUI

### ISSUE THREAD

**Issue by RipleyTom** [ogri-la/strongbox#400]
Strongbox seems to have trouble updating ElvUI:
![image](https://user-images.githubusercontent.com/6031700/235849602-8f2b8c2c-aaa8-4a30-ac74-9affcba66095.png)
This image is after updating ElvUI to 13.30.
The "dependencies"(which I think are just the different parts of the mods) don't seem to update properly.
After clicking Update the Update option is still available(though it doesn't seem to do anything as 13.30 is already installed from its pov).

I just came back to wow and when updating my modlist I noticed ElvUI wasn't updating properly. At the time I deleted it from the modlist and installed it anew thinking that maybe my version was so old that it created an issue but it seems to be the same with the recent wow version change.

Reproduction step:
1) Install any old version of ElvUI.
2) Try to update

Expected:
Dependencies updating properly.

Edit:
In wow the differents parts of ElvUI were tagged as out of date after updating through strongbox.
Updating manually by extracting the zip from tukui did fix it however strongbox still reports version 13.29 for the dependencies.

**Comment by torkus** [comment]
ok, found one issue with installing ElvUI that is on their side rather than mine. Their API appears to be returning malformed HTTP for the ElvUI addon at https://www.tukui.org/classic-wotlk-addons.php?id=2

```bash
$ curl -v --http1.1 https://www.tukui.org/classic-wotlk-addons.php?download=2
*   Trying 54.39.107.238:443...
* Connected to www.tukui.org (54.39.107.238) port 443 (#0)
* ALPN: offers http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=tukui.org
*  start date: Feb 28 05:49:19 2023 GMT
*  expire date: May 29 05:49:18 2023 GMT
*  subjectAltName: host "www.tukui.org" matched cert's "www.tukui.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/1.1
> GET /classic-wotlk-addons.php?download=2 HTTP/1.1
> Host: www.tukui.org
> User-Agent: curl/8.0.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sun, 07 May 2023 01:21:25 GMT
< Server: Apache/2.4.25
< Content-Disposition: attachment; filename=
< Set-Cookie: Tukui_c00k1es_u=1; expires=Mon, 06-May-2024 01:21:25 GMT; path=/; domain=tukui.org; secure; HttpOnly
< Set-Cookie: Tukui_c00k1es_k=; expires=Mon, 06-May-2024 01:21:25 GMT; path=/; domain=tukui.org; secure; HttpOnly
< Set-Cookie: Tukui_c00k1es_sid=4fec71233ec83ad12ee558761028d6a5; expires=Mon, 06-May-2024 01:21:25 GMT; path=/; domain=tukui.org; secure; HttpOnly
* Invalid Content-Length: value
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
curl: (8) Invalid Content-Length: value
```

With this being the culprit:

> * Invalid Content-Length: value

strongbox assumes that there is either a valid value there or nothing. 

I have a fix for that but the larger problem is that the ElvUI addon is no longer at that location, which means the strongbox catalogue is incorrect. My investigation continues ...

**Comment by torkus** [comment]
ok, I think this is fixed in 6.1.1 just released, let me know if it doesn't work for you and I'll re-open and re-investigate.

**Comment by RipleyTom** [comment]
It's indeed fixed, thank you for the quick fix!

**Comment by torkus** [comment]
I'm glad the fix worked.

Thanks for reporting the bug, I probably wouldn't have caught it otherwise.
