### ISSUE TITLE
Can Windows users execute with JDK?

### ISSUE THREAD

**Issue by Char11e** [ogri-la/strongbox#423]
At present, I tried to use JDK to run on Win 10, and found that the program did not respond.

**Comment by torkus** [comment]
Windows is not supported. Strongbox is built for Linux and is tested on macOS but I'm certain that it won't work properly on Windows even if you could even get it running. Sorry.

**Comment by torkus** [comment]
I do maintain a list of other addon managers for WoW. Here is a list of addon managers that support Windows with a GUI:

https://ogri-la.github.io/wow-addon-managers/?preset/name=default&field/maintained=yes&field/retail=yes&field/classic=yes&field/windows=yes&field/ui=GUI

**Comment by Char11e** [comment]
Thank you for sharing your information.

Because I am looking for a manager that supports custom gitlab or github addon library sources, and currently I only find that your program supports it.

**Comment by torkus** [comment]
Strongbox does support addons from github and gitlab using 'releases' but not plain git repositories.

I could have sworn Instawow supported github as well, but I can't find out how from the GUI. From the README it may be possible from the CLI: https://github.com/layday/instawow?tab=readme-ov-file#cli-operation

Instawow and Strongbox use a catalogue of github addons:
https://github.com/ogri-la/strongbox-catalogue/blob/master/github-catalogue.json

If you wanted inclusion on that list I could offer some advice. Are your repositories public?

**Comment by Char11e** [comment]
Our repository is expected to be public.
In addition, we will use GitHub's Release tag as a basis for comparison of version numbers.

https://addons.miliui.com/
Because we are a Traditional Chinese UI community, we currently want to solve the inconvenience of users manually downloading the addon compressed package.

**Comment by torkus** [comment]
well, if you're going to host addons in Github repositories and if those repositories use the topic/tag `wow-addon` or `world-of-warcraft` or `addon` like this:

![Screenshot at 2023-12-26 21-23-54](https://github.com/ogri-la/strongbox/assets/48790775/1c96a2f3-b8d8-4842-9668-14aca2c8cb76)

then it will be discovered by the Github catalogue builder and incorporated into the Github catalogue and would then be available to download from instawow (and strongbox too, if any of your users are on linux/mac).

do you run https://addons.miliui.com/ ? It looks fairly large. If it had an API then integrating with it directly would be another option.

**Comment by Char11e** [comment]
Thank you for sharing.
I'm just one of the co-moderators of that forum.

I'm currently investigating your code and trying to compile it into a windows executable jar file using leiningen.

It might be a good idea to use something like the curseforge API.
Translated with DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by torkus** [comment]
> It might be a good idea to use something like the curseforge API.

Curseforge support was removed in version 5.0.0, released Feb 1st, 2022. It won't be coming back.

**Comment by layday** [comment]
> I could have sworn Instawow supported github as well, but I can't find out how from the GUI.

By pasting the repo URL in the search bar, which I suppose is less obvious than I imagined :)
